### ISSUE TITLE
header问题

### ISSUE THREAD

**Issue by YangZhiqiang98** [Famine-Life/bbw-tp#4]
我的header是乱的

**Comment by Famine-Life** [comment]
给下报错信息



---原始邮件---
发件人: "YangZhiqiang98"<notifications@github.com&gt;
发送时间: 2020年4月10日(周五) 下午5:48
收件人: "Famine-Life/bbw-tp"<bbw-tp@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Famine-Life/bbw-tp] header问题 (#4)




 
我的header是乱的

**Comment by YangZhiqiang98** [comment]
![image](https://user-images.githubusercontent.com/34591611/78983925-be1a7e80-7b57-11ea-9bd8-a6e2cff140f2.png)

**Comment by YangZhiqiang98** [comment]
![image](https://user-images.githubusercontent.com/34591611/78984175-35501280-7b58-11ea-8f66-4f98bbfaebad.png)
这是我clone您的代码的运行截图。

**Comment by Famine-Life** [comment]
你的css文件没有加载，**F12**应该会看到有报错。

**Comment by YangZhiqiang98** [comment]
解决了。刷新的时候右键，选择"清除缓存并进行硬刷新”，就ok了。这是什么原因呢
