### ISSUE TITLE
请问一下为什么会出现错误，非法操作得页面呢

### ISSUE THREAD

**Issue by MutekiStarpolajiang** [Famine-Life/bbw-tp#8]

**Comment by Famine-Life** [comment]
1，后台抛异常了
2，设了权限



---原始邮件---
发件人: "MutekiStarpolajiang"<notifications@github.com&gt;
发送时间: 2020年7月2日(周四) 中午12:11
收件人: "Famine-Life/bbw-tp"<bbw-tp@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Famine-Life/bbw-tp] 请问一下为什么会出现错误，非法操作得页面呢 (#8)

**Comment by MutekiStarpolajiang** [comment]
好的谢谢





------------------ 原始邮件 ------------------
发件人: 练涛 <notifications@github.com&gt;
发送时间: 2020年7月2日 12:45
收件人: Famine-Life/bbw-tp <bbw-tp@noreply.github.com&gt;
抄送: MutekiStarpolajiang <1294467544@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Famine-Life/bbw-tp] 请问一下为什么会出现错误，非法操作得页面呢 (#8)





 1，后台抛异常了 
 2，设了权限 
 
 
 
 ---原始邮件--- 
 发件人: "MutekiStarpolajiang"<notifications@github.com&amp;gt; 
 发送时间: 2020年7月2日(周四) 中午12:11 
 收件人: "Famine-Life/bbw-tp"<bbw-tp@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: [Famine-Life/bbw-tp] 请问一下为什么会出现错误，非法操作得页面呢 (#8)
